### ISSUE TITLE
Unplayable Darkness

### ISSUE THREAD

**Issue by nbystrom** [munificent/hauberk#37]
I've frequently encountered the problem that it is so dark in the dungeon that I am unable to see enemies in the square adjacent to me. It may be a design concept, however when I encounter areas like that, I've taken to avoiding them altogether or even quitting the game because it simply isn't enjoyable anymore.  
Please understand that I do enjoy the darkness - it's exciting to be in an area where you don't quite know where your enemies are. It's just not as exciting when you're in an area where you have to punch the wall to know it's there, and you used your last light source on all the other areas like this one.

**Comment by munificent** [comment]
Yeah, there's still a lot of tuning and tweaking to do around the still-relatively-new lighting mechanics. Note that you don't need to *use* a light source for it to illuminate. If you just carry them around, they will provide a glow around you and last forever. Using one just permanently illuminates a larger radius.

So, in general, you probably don't want to consume your last candle. Just hold it until you find more.

Thanks for the feedback! I'm going to close this because I don't have a specific change to implement for it, but I'll keep this in mind.

**Comment by nbystrom** [comment]
Thanks! I'm loving the game so far, so I can't wait to see what you do next!
